package br.com.fiap.trip.datastore.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
@ToString
@DynamoDBTable(tableName = "trip")
public class TripEntity {

	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "id")
	private String id;

	@DynamoDBIndexRangeKey(attributeName = "date", localSecondaryIndexName = "dateIndex")
	private String date;

	@DynamoDBAttribute(attributeName = "country")
	private String country;

	@DynamoDBAttribute(attributeName = "city")
	private String city;

	@DynamoDBAttribute(attributeName = "urlRepository")
	private String urlRepository;
}
