AWSTemplateFormatVersion: '2010-09-09'
Description: 'study-datalake Rest API to manage a Data Lake of study links '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateTripFunction:
    Description: CreateTrip Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripFunction
      - Arn
  SearchTripByIdFunction:
    Description: SearchTripById Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SearchTripByIdFunction
      - Arn
  SearchTripByDateFunction:
    Description: SearchTripByDate Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SearchTripByDateFunction
      - Arn
Resources:
  CreateTripFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f # validar url
      Events:
        CreateTrip:
          Properties:
            Method: post
            Path: /trip
          Type: Api
      Handler: br.com.fiap.trip.serverless.handler.CreateTrip::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  SearchTripByIdFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        SearchTripById:
          Properties:
            Method: get
            Path: /trip/{id}
          Type: Api
      Handler: br.com.fiap.trip.serverless.handler.SearchTripById::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  SearchTripByDateFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        SearchTripByDate:
          Properties:
            Method: get
            Path: /trip/period
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
          Type: Api
      Handler: br.com.fiap.trip.serverless.handler.SearchTripByDate::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31